import { ScrollView , ListView, Button } from "std-widgets.slint";
import { State } from "../state.slint";

export component ShowFile inherits Rectangle {
    in property <[string]> file_text : ["", "", ""];

    VerticalLayout {
        spacing: 20px;
        width: 100%;

        HorizontalLayout {
        ListView { 
            padding-left: 10px;
            min-width: 500px;
            for data in [
                {text : file-text},
            ] : VerticalLayout {
                Text {
                    text: file-text[0];
                    wrap: word-wrap;
                    font-size: 14px; 
                }
                Text {
                    color: red;
                    text: file-text[1];
                    wrap: word-wrap;
                    font-size: 14px; 
                }
                Text {
                    color: red;
                    text: file-text[2];
                    wrap: word-wrap;
                    font-size: 14px; 
                }
            }
        }
    }
}
}
