import { ComboBox, CheckBox } from "std-widgets.slint";
import { comp, OpButton } from "common.slint";
import { State } from "../state.slint";

export component Desprotect inherits Rectangle{
    in-out property <[string]> errors;
    in-out property <[bool]> inProgress;

    HorizontalLayout {
        padding: 15px;
        Text {
            horizontal-alignment: center;
            text: "Desproteger";
            font-size: 18px;
        }
    }
    HorizontalLayout {
        alignment: center;
        width: 100%;
        spacing: 15px;
        padding-top: 50px;
        VerticalLayout {
            alignment: start;
            correct := CheckBox { 
                text: "  Corrección ";
                checked: State.correct;
                toggled => {
                    State.correct = !State.correct
                }
            }
        }
        OpButton {
            text: "Elegir Archivo";
            clicked => { State.desprotect(State.correct) }
        }
    }
    VerticalLayout {
        padding-top: 80px;
        padding-bottom: 15px;
        padding-left: 15px;
        padding-right: 15px;
        comp{}
    } 
}
