import { ComboBox } from "std-widgets.slint";
import { comp, OpButton } from "common.slint";
import { State } from "../state.slint";

export component Protect inherits Rectangle{
    in-out property <[string]> errors;
    in-out property <[bool]> inProgress;

    HorizontalLayout {
        padding: 15px;
        Text {
            horizontal-alignment: center;
            text: "Proteger";
            font-size: 18px;
        }
    }
    HorizontalLayout {
        alignment: center;
        width: 100%;
        spacing: 15px;
        padding-top: 50px;
        Text {
            horizontal-alignment: center;
            text: "  Tamaño de bloque: ";
        }
        combo-box := ComboBox {
            width: 100px;
            height: 30px;
            current-value: State.block-size;
            model: ["32", "2048", "65536"];
            selected => {
                State.block-size = self.current-value;
            }
        }
        OpButton {
            text: "Elegir Archivo";
            clicked => { State.protect(combo-box.current-value) }
        }
        if errors[0] != "" : Text {
            text: errors[0];
        }
    }
    
    VerticalLayout {
        padding-top: 80px;
        padding-bottom: 15px;
        padding-left: 15px;
        padding-right: 15px;
        comp{}
    } 
}
