import { StyleMetrics , Button} from "std-widgets.slint";

component MenuItem inherits Rectangle {
    in property<string> name <=> t.text;
    in-out property<bool> active;
    background: root.active ? rgba(100%, 100%, 100%, 14%) : ma.has-hover ? rgba(100%, 100%, 100%, 9%) : transparent;
    ma := TouchArea {}
    HorizontalLayout {
        alignment: center;
        spacing: 6px;
        padding: 8px;
        padding-left: 30px;
        padding-right: 30px;
        t := Text {
            vertical-alignment: center;
            color: black;
            font-size: 15px;
        }
    }
}

export component MenuBar inherits Rectangle {
    background: lightskyblue;
    property<int> active: 0;
    min-width: 180px;
    max-width: 250px;
    VerticalLayout {
        height: 100%;
        padding-left: 0px;
        padding-top: 35px;
        padding-right: 0px;
        padding-bottom: 200px;
        spacing: 8px;
        VerticalLayout {
            padding-left: 50px;
            padding-top: 0px;
            padding-right: 50px;
            padding-bottom: 54px;
        }

        for entry[idx] in [
            { name: "Principal", tab: "main"},
            { name: "Proteger", tab: "proteger"},
            { name: "Desproteger", tab:"desproteger"},
            { name: "Corromper", tab:"corromper"},
            { name: "Comprimir", tab: "corrompir"},
            { name: "Descomprimir", tab: "descomprimir"},
        ] : VerticalLayout{
            MenuItem {
            name: entry.name;
            active: root.active == idx;
            }
            
            out property <string> tab-active: entry.tab;
        }
    }
}