import { Operations } from "operations.slint";
import { Statistics } from "statistics.slint";
import { State } from "state.slint";
import { Button , TabWidget} from "std-widgets.slint";

export { State }

struct ButtonData {
    text: string,
    operation: string,
}

export component MainWindow inherits Window {
    in-out property <string> error : "" ;
    in-out property <string> message : "" ;

    min-width: 800px;
    min-height: 500px;

    VerticalLayout {
        if error != "" : Text {
            text: error;
        }
        if message != "" : Text {
            text: message;
        }

        TabWidget { 
            Tab {
                title: "Operaciones";
                Operations {}
            }
            Tab {
                title: "Estadísticas";
                Statistics {}
            }
        }
    }
}
