import { Compare } from "./files/compare.slint";
import { Corrupt } from "./operations/corrupt.slint";
import { Compress } from "./operations/compress.slint";
import { Protect } from "./operations/protect.slint";
import { Desprotect } from "./operations/desprotect.slint";
import { Decompress } from "./operations/decompress.slint";
import { Statistics } from "./operations/statistics.slint";
import { HuffmanStats, HammingStats, HuffmanEntry } from "./operations/statistics.slint";
import { State } from "state.slint";
import { Button , TabWidget} from "std-widgets.slint";
import { Principal } from "principal.slint";
import { MenuBar } from "menu.slint";
export { State }

component MainWindow inherits Window {
    title: "Teoria de la Informacion";
    in-out property <[string]> errors : ["", "", "", "", ""];
    in-out property <[bool]> inProgress : [false, false, false, false, false];

    in-out property <[string]> orig-text;
    in-out property <[string]> proc-text;

    in-out property <[string]> stat : [""];
    in-out property <[HammingStats]> hamming-stats;
    in-out property <[HuffmanStats]> huffman-stats;
    in-out property <[HuffmanEntry]> huffman-table;

    in-out property <string> active-tab : "Pantalla Principal";

    min-width: 1000px;
    min-height: 800px;

    padding: 0;
    VerticalLayout {
        spacing: 0;
        HorizontalLayout {
            height: 100%;
            spacing: 5px;

            MenuBar {
                pantalla <=> active-tab;
            }
            HorizontalLayout {
                spacing: 6px;

                if active-tab == "Pantalla Principal" : Principal {}

                if active-tab == "Proteger" : Protect {
                    errors: errors;
                    inProgress: inProgress;
                }
                if active-tab == "Desproteger" : Desprotect {
                    errors: errors;
                    inProgress: inProgress;
                }
                if active-tab == "Corromper" : Corrupt {}

                if active-tab == "Comprimir" : Compress {}

                if active-tab == "Descomprimir" : Decompress {}

                if active-tab == "Comparar" : Compare {
                    file-text: orig-text;
                }
                if active-tab == "stats" : Statistics {
                    stat : stat[0];
                    hamming-stats : hamming-stats[0];
                    huffman-stats : huffman-stats[0];
                    huffman-table : huffman-table;
                }
            }
        }
    }
}
