import { StyleMetrics , Button} from "std-widgets.slint";

component MenuItem inherits Rectangle {
    in property<string> name <=> t.text;
    in-out property<bool> active;
    in-out property <string> tab;
    in-out property <string> active-tab : "Pantalla Principal";
    background: active-tab==tab ? rgba(100%, 100%, 100%, 20%) : ma.has-hover ? rgba(100%, 100%, 100%, 9%) : transparent;

    ma := TouchArea {
        clicked => { active-tab = tab;}
    }
    HorizontalLayout {
        alignment: center;
        spacing: 6px;
        padding: 8px;
        padding-left: 30px;
        padding-right: 30px;
        t := Text {
            vertical-alignment: center;
            color: black;
            font-size: 15px;
        }
    }
}

export component MenuBar inherits Rectangle {
    background: lightskyblue;
    in-out property <string> pantalla;
    property<int> active: 0;
    min-width: 170px;
    max-width: 170px;
    VerticalLayout {
        height: 100%;
        padding-left: 0px;
        padding-top: 35px;
        padding-right: 0px;
        padding-bottom: 200px;
        spacing: 8px;
        VerticalLayout {
            padding-left: 50px;
            padding-top: 0px;
            padding-right: 50px;
            padding-bottom: 54px;
        }

        for entry[idx] in [
            { name: "Principal", tab: "Pantalla Principal"},
            { name: "Proteger", tab: "Proteger"},
            { name: "Desproteger", tab:"Desproteger"},
            { name: "Corromper", tab:"Corromper"},
            { name: "Comprimir", tab: "Comprimir"},
            { name: "Descomprimir", tab: "Descomprimir"},
            { name: "Comparar", tab: "Comparar"},
            { name: "Estadisticas", tab: "stats"},
        ] : VerticalLayout{
            MenuItem {
                name: entry.name;
                active: root.active == idx;
                tab: entry.tab;
                active-tab <=> pantalla;
            }
        }
    }
}
