import { Button, HorizontalBox , ScrollView , ComboBox, CheckBox, LineEdit, GroupBox} from "std-widgets.slint";
import { State } from "state.slint";
import { Statistics } from "statistics.slint";


component OpButton inherits Button {
    width: 150px;
    height: 30px;
}

component comp inherits Rectangle{
    VerticalLayout {
        width: 100%;
        height: 100%;
        padding-top: 20px;
        spacing: 20px;
        t:=Text{
            text: "ORIGINAL";
            padding-top: 10px;
        }
        Statistics {}
        
        p:=Text{
            text: "PROCESADO";
            padding-top: 10px;
        }
        Statistics {}
        
    }

}


export component proteger inherits Rectangle{
    in-out property <[string]> errors;
    in-out property <[bool]> inProgress;
    HorizontalLayout {
        padding: 15px;
        Text {
            horizontal-alignment: center;
            text: "Proteger";
            font-size: 18px;
        }
    }
    HorizontalLayout {
        alignment: center;
        width: 100%;
        spacing: 15px;
        padding-top: 50px;
        Text {
            horizontal-alignment: center;
            text: "  Tamaño de bloque: ";
        }
        combo-box := ComboBox {
            width: 100px;
            height: 30px;
            current-value: State.block-size;
            model: ["32", "2048", "65536"];
            selected => {
                State.block-size = self.current-value;
            }
        }
        OpButton {
            text: "Elegir Archivo";
            clicked => { State.protect(combo-box.current-value) }
        }
        if errors[0] != "" : Text {
            text: errors[0];
        }
    }
    
    VerticalLayout {
        padding-top: 80px;
        padding-bottom: 15px;
        padding-left: 15px;
        padding-right: 15px;
        comp{}
    } 

}

export component desproteger inherits Rectangle{
    in-out property <[string]> errors;
    in-out property <[bool]> inProgress;
    HorizontalLayout {
        padding: 15px;
        Text {
            horizontal-alignment: center;
            text: "Desproteger";
            font-size: 18px;
        }
    }
    HorizontalLayout {
        alignment: center;
        width: 100%;
        spacing: 15px;
        padding-top: 50px;
        VerticalLayout {
            alignment: start;
            correct := CheckBox { 
                text: "  Corrección ";
                checked: State.correct;
                toggled => {
                    State.correct = !State.correct
                }
            }
        }
        
        OpButton {
            text: "Elegir Archivo";
            clicked => { State.desprotect(State.correct) }
        }
    }

    VerticalLayout {
        padding-top: 80px;
        padding-bottom: 15px;
        padding-left: 15px;
        padding-right: 15px;
        comp{}
    } 
    
}

export component corromper inherits Rectangle {
    HorizontalLayout {
        padding: 15px;
        alignment: center;
        Text {
            text: "Corromper:   ";
            font-size: 18px;
        }
        
        Text{
            text: "Ingresar las probabilidades";
            font-size: 18px;
        }
    }
    HorizontalLayout {
        spacing: 10px;
        alignment: center;
        padding-top: 50px;
        Text{
            text: "Primer error";
            font-size: 14px;
        }
        p1:=LineEdit {
            width: 100px;
            height: 30px;
            font-size: 14px;
            text: 1.6;
            edited => {State.probability1=p1.text.to-float()}
        }
        
        Text{
            text: "Segundo error";
            font-size: 14px;
        }
        p2:=LineEdit {
            width: 100px;
            height: 30px;
            font-size: 14px;
            text: 0.0;
            edited => {State.probability2=p2.text.to-float()}
        }
        
        VerticalLayout {
            padding: 10px;
            if(((p1.text.to-float()+p2.text.to-float())>1) || ((p1.text.to-float()+p2.text.to-float())<0)): Text {
                text: "La suma debe ser menor igual a uno y mayor a cero";
                font-size: 14px;
            }
        }
         
        if(((p1.text.to-float()+p2.text.to-float())<=1) && ((p1.text.to-float()+p2.text.to-float())>=0)): OpButton {
            text: "Elegir Archivo";
            clicked => { State.corrupt(State.probability1, State.probability2);
            }
        }
    }    
        
    VerticalLayout {
        padding-top: 80px;
        padding-bottom: 15px;
        padding-left: 15px;
        padding-right: 15px;
        comp{}
    } 
}

export component comprimir inherits Rectangle{
    HorizontalLayout {
        padding: 15px;
        Text {
            horizontal-alignment: center;
            text: "Comprimir";
            font-size: 18px;
        }
    }
    HorizontalLayout {
        alignment: center;
        padding-top: 50px;
        OpButton {
            text: "Elegir Archivo";
            clicked => { State.compress() }
        }
    }

    VerticalLayout {
        padding-top: 80px;
        padding-bottom: 15px;
        padding-left: 15px;
        padding-right: 15px;
        comp{}
    } 
    
}

export component descomprimir inherits Rectangle{
    HorizontalLayout {
        padding: 15px;
        Text {
            horizontal-alignment: center;
            text: "Descomprimir";
            font-size: 18px;
        }
    }
    HorizontalLayout{
        alignment: center;
        padding-top: 50px;
        OpButton {
        text: "Elegir Archivo";
        clicked => { State.decompress() }
    }
    }
    VerticalLayout {
        padding-top: 80px;
        padding-bottom: 15px;
        padding-left: 15px;
        padding-right: 15px;
        comp{}
    }    
}

