import { ListView } from "std-widgets.slint";
export component Principal inherits Rectangle {
    VerticalLayout {
        height: 100%;
        width: 100%;
        spacing: 10px;

        for entry[idx] in [
                { name: "Trabajo Practico de Maquina"},
                { name: "Teoria de la informacion"},
                { name: "Profesor: Silvestri"},
                { name: "Alumnos: Brocas Ivan y Loyola Luciana"},
            ] : VerticalLayout{
                t := Text{
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    text: entry.name;
                    font-size: 20px;
                }                
            }
        
    }
}
