export component Principal inherits Rectangle {
    GridLayout {
        padding: 15px;
        width: 700px;
        spacing: 20px;
        
        Text {
            row: 0;
            col: 1;
            vertical-alignment: center;
            text: "  Practico de Maquina  ";
            font-size: 20px;
        }
        Text {
            row: 1;
            col: 1;
            vertical-alignment: center;
            text: "  Hamming y Huffman  ";
            font-size: 20px;
        }
        Text {
            row: 2;
            col: 1;
            vertical-alignment: center;
            text: "  Brocas Ivan y Loyola Luciana  ";
            font-size: 20px;
        }
        
    }
}
