export global State {
    callback protect(string);
    callback desprotect(bool);
    callback corrupt(float, float);
    callback compress();
    callback decompress();
    callback choose_file();

    in-out property <string> block_size : "32";
    in-out property <bool> correct : true;
    in-out property <float> probability1 : 0.0 ;
    in-out property <float> probability2 : 0.0 ;
    in-out property <string> path;
}
