import { ScrollView , ListView, Button} from "std-widgets.slint";
import { State } from "state.slint";

export component Statistics inherits Rectangle {
    in property <[string]> file_text : ["", "", ""];

    VerticalLayout {
        padding-top: 15px;
        spacing: 20px;
        

        HorizontalLayout {
        ListView { 
            padding-left: 10px;
            width: 500px;
            for data in [
                {text : file-text},
            ] : VerticalLayout {
                Text {
                    text: file-text[0];
                    wrap: word-wrap;
                }
                Text {
                    text: file-text[1];
                    wrap: word-wrap;
                }
                Text {
                    text: file-text[2];
                    wrap: word-wrap;
                }
            }
        }
    }
}
}
